Transaction as dependency
uestla/YetORM pull request #21
Opened 2019-03-27 14:29 UTC by pupitooo

Z venku nelze použít `NdbContext::beginTransaction`, proto je potřeba vložit Transation jako závislost.

2019-03-27 17:41 UTC, uestla requested changes

2019-03-27 17:41 UTC, uestla commented on src/YetORM/Repository.php
> +	public function __construct(NdbContext $database, ?Transaction $transaction = null)
Please no PHP7 syntax yet.

```suggestion
	public function __construct(NdbContext $database, Transaction $transaction = null)
```

2019-03-27 17:41 UTC, uestla commented on src/YetORM/Repository.php
> +		$this->transaction = $transaction ?? new Transaction($database->getConnection());
Please no PHP7 syntax yet.

```suggestion
		$this->transaction = $transaction ?: new Transaction($database->getConnection());
```

2019-03-27 17:42 UTC, uestla commented
Děkuji!
Mohu poprosit ukázku kódu, kvůli kterému toto navrhujete?

2019-03-27 17:47 UTC, pupitooo commented
Kód bych asi poslal jen ilustrativní, takže se radši pokusím popsat slovně. Jedná se o vytvoření faktury. Při jejím vytvoření persistuju více entit. Dílčí ukládání je ve fasádách. A celý tento proces potřebuji vrátit, pokud někde dojde k chybě. V tomto případě mi to při použití `NdbContext::beginTransaction` hlásí chybu při prvním persistování.
Stačí tenhle popis?

2019-03-27 18:42 UTC, uestla commented
Rozumím, děkuji za popis. Pomohl by tento kód?

```php
// InvoiceFacade.php

(new Transaction($ndbContext))->transaction(function () {
   $this->repositoryOne->persist($entityOne);
   $this->repositoryTwo->persist($entityTwo);
});
```

Vrstva pro transakce se přidávala právě kvůli transakci v každé `persist()` metodě repozitářů, tak aby byly řešené takto "vnořené" transakce. Proto je pak nutné tuhle vrstvu používat i jinde.

2019-03-28 09:31 UTC, pupitooo commented
Takhle to může jít a na mém případu to prochází. Díky za pomoc. Díky té metodě `transaction` tohle není potřeba.

2019-03-29 08:34 UTC, uestla commented
To jsem rád. Transakční vrstva by asi měla být zmíněna v dokumentaci / README.

Zkusím to tam přidat - nebo mi s tím můžete pomoct ;-)

2020-04-10 11:59 UTC, uestla commented
Closing as inactive.

2020-04-10 11:59 UTC, closed without merging